export const caminhoImagem = [
    {
        numero: 10,
        path: '../logo-partidos/10.png'
    }, {
        numero: 11,
        path: '../logo-partidos/11.png'
    }, {
        numero: 12,
        path: '../logo-partidos/12.png'
    }, {
        numero: 13,
        path: '../logo-partidos/13.png'
    }, {
        numero: 14,
        path: '../logo-partidos/14.png'
    }, {
        numero: 15,
        path: '../logo-partidos/15.png'
    }, {
        numero: 16,
        path: '../logo-partidos/16.png'
    }, {
        numero: 17,
        path: '../logo-partidos/17.png'
    }, {
        numero: 18,
        path: '../logo-partidos/18.png'
    }, {
        numero: 19,
        path: '../logo-partidos/19.png'
    }, {
        numero: 20,
        path: '../logo-partidos/20.png'
    }, {
        numero: 21,
        path: '../logo-partidos/21.png'
    }, {
        numero: 22,
        path: '../logo-partidos/22.png'
    }, {
        numero: 23,
        path: '../logo-partidos/23.png'
    }, {
        numero: 27,
        path: '../logo-partidos/27.png'
    }, {
        numero: 28,
        path: '../logo-partidos/28.png'
    }, {
        numero: 29,
        path: '../logo-partidos/29.png'
    }, {
        numero: 30,
        path: '../logo-partidos/30.png'
    }, {
        numero: 33,
        path: '../logo-partidos/33.png'
    }, {
        numero: 35,
        path: '../logo-partidos/35.png'
    }, {
        numero: 36,
        path: '../logo-partidos/36.png'
    }, {
        numero: 40,
        path: '../logo-partidos/40.png'
    }, {
        numero: 43,
        path: '../logo-partidos/43.png'
    }, {
        numero: 44,
        path: '../logo-partidos/44.png'
    }, {
        numero: 45,
        path: '../logo-partidos/45.png'
    }, {
        numero: 50,
        path: '../logo-partidos/50.png'
    }, {
        numero: 51,
        path: '../logo-partidos/51.png'
    }, {
        numero: 55,
        path: '../logo-partidos/55.png'
    }, {
        numero: 65,
        path: '../logo-partidos/65.png'
    }, {
        numero: 70,
        path: '../logo-partidos/70.png'
    }, {
        numero: 77,
        path: '../logo-partidos/77.png'
    }, {
        numero: 80,
        path: '../logo-partidos/80.png'
    }, {
        numero: 90,
        path: '../logo-partidos/90.png'
    },
    
]